[build]
command = "npm run build"
publish = "dist"

[build.environment]


VITE_GEMINI_API_KEY = "$VITE_GEMINI_API_KEY"

SECRETS_SCAN_OMIT_KEYS = "VITE_GEMINI_API_KEY"
SECRETS_SCAN_OMIT_PATHS = "dist/assets/*.js"

[secrets_scanning]

omit_keys = ["VITE_GEMINI_API_KEY"]


omit_paths = ["dist/assets/*.js"]

[[redirects]]

from = "/*"
to = "/index.html"
status = 200